package com.github.abigail830.ThanosContractService.exception;

public enum ErrorCode {
    INVALID_SCHEMA_KEY,
    SCHEMA_NOT_EXIST_FOR_UPDATE,
    INVALID_SCHEMA_FOR_UPDATE,

    CONTRACT_NOT_EXIST_FOR_UPDATE,
    INVALID_CONTRACT_FOR_UPDATE,
    INVALID_CONTRACT_INDEX,
    CONTRACT_NOT_FOUND,


}
